collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  load_paths:
    - _sass
    - _vendor/bootstrap

kramdown:
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
